# var = input("enter anything: ")
# print(type(var))
# var1 = int(input("enter a number: "))
# print(type(var1))
# var2 = float(input("enter a decimal number: "))
# print(type(var2))
print(type(False))
print(type("a"))
print(type(254.65))
print(type(56))
